partitionType: EQUALGRID
# EQUALGRID HILBERT RTREE VORONOI QUADTREE KDBTREE
indexType: QUAD_TREE
# STR_TREE QUAD_TREE
partitions: 1
decimals: 19

#kafka:


#local or remote
local: true

#locations
publicationLocation: D:\projects\diplomski\geofil-storm\publications19.json
subscriptionLocation: D:\projects\diplomski\geofil-storm\subscriptions19.json

